In [1]:
import gym_envs
import gym 

import matplotlib.pyplot as plt

In [2]:
env = gym.make('gym_envs/GridWorld-v0', render_mode = "human")

In [3]:
env.action_space.seed(42)

observation, info = env.reset(seed=42)

for _ in range(100):
    observation, reward, terminated, truncated, info = env.step(env.action_space.sample())

    if terminated or truncated:
        observation, info = env.reset()

env.close()




c:\Python310\lib\site-packages\gym\utils\passive_env_checker.py:187: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.warn(


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [21]:
observation

{'agent': array([1, 5]), 'target': array([6, 4])}

In [22]:
info

{'distance': 6.0}

In [ ]:
env.close()

In [6]:
import numpy as np

In [209]:
try1 = np.zeros((10,10))

In [20]:
try1

array([[0., 3., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [224]:
import random

In [290]:
"""
randomly putting sources into different places and there is no specific number of sources.
"""
try1[1:9, 1:9] = np.random.randint(low=2, size=(8,8))

init_sum = int(np.count_nonzero(try1==1))

"""
This is the process where assigning extra sources(1) into 0 randomly.
"""
if init_sum > 20:
    row_list = np.nonzero(try1)[0]
    column_list = np.nonzero(try1)[1]
    diff_sum = init_sum - 20

    alist = list(range(len(row_list)))
    list_del = random.sample(alist, k = diff_sum)

    for i in list_del:
        try1[row_list[i]][column_list[i]] = 0


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
20


In [227]:
print(np.count_nonzero(try1==1))

39


In [223]:
np.nonzero(try1)#

(array([1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
        6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8], dtype=int64),
 array([4, 2, 3, 4, 5, 6, 7, 8, 1, 5, 6, 7, 2, 3, 4, 6, 7, 8, 1, 3, 4, 7,
        1, 5, 6, 8, 1, 2, 3, 4, 5, 6, 7, 2, 3, 5, 8], dtype=int64))

In [219]:
np.where(try1 != 1, try1, 2 )

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 2., 2., 2., 2., 2., 2., 2., 0.],
       [0., 2., 0., 0., 0., 2., 2., 2., 0., 0.],
       [0., 0., 2., 2., 2., 0., 2., 2., 2., 0.],
       [0., 2., 0., 2., 2., 0., 0., 2., 0., 0.],
       [0., 2., 0., 0., 0., 2., 2., 0., 2., 0.],
       [0., 2., 2., 2., 2., 2., 2., 2., 0., 0.],
       [0., 0., 2., 2., 0., 2., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [275]:
random.sample([0,1,2,3,4,5,6], k = 2)

[0, 1]